version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
  - package-ecosystem: npm
    directory: "/js"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
