matrix:
  include:
    - language: python
      python: "3.6"
      cache: pip
      addons:
        apt:
          packages:
            - libicu-dev
      before_install:
        # - sudo apt-get -qq update
        # - sudo apt-get install -y libicu-dev
        - pip install -e ".[dev]"
      script:
        - nosetests --with-coverage --cover-package=followthemoney --cover-erase
      after_success:
        # push tag as well
        - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
            python setup.py sdist bdist_wheel ;
            twine upload dist/* ;
            cd enrich && python setup.py sdist bdist_wheel && twine upload dist/* ;
            cd ../integrate && python setup.py sdist bdist_wheel && twine upload dist/* ;
          fi
    - language: node_js
      cache: npm
      node_js: "11"
      before_install:
        - cd js
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      install:
        - npm install
        - npm run build
      script:
        - npm run test:prod && npm run lint
      after_success:
        - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
            npm run build ;
            npm publish ;
          fi